### ISSUE TITLE
Add tests and better documentation

### ISSUE THREAD

**Issue by elfey** [beeplin/feathers-cache#1]
This looks great, I just wish there were some tests and the documentation was a little bit better.

**Comment by beeplin** [comment]
i m working on a more full-featured version of this. :)

**Comment by theonlyelf** [comment]
@beeplin keep me updated (I'll watch the repo)! I'm super interested in it and I think this whole concept is really intelligent.

**Comment by beeplin** [comment]
@elfey this repo is deprecated since the feathers core team now has `feathers-offline-realtime` etc. to serve this purpose. ;)
